# Generated by Django 2.2.2 on 2019-07-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_tile',
            new_name='song_title',
        ),
    ]
